# Numpy Einführung

```{contents}
```


<a id="Numpy_kurze_Beschreibung">
    
## Kurze Beschreibung
</a>

NumPy, kurz für "Numerical Python", ist eine der wichtigsten und weit verbreiteten Python-Bibliotheken für numerische Berechnungen und wissenschaftliches Rechnen. Die Bibliothek bietet leistungsstarke Datenstrukturen und Funktionen, die speziell für das Arbeiten mit großen Datenmengen und numerischen Berechnungen entwickelt wurden.

Hier sind einige der Hauptmerkmale und Funktionen von NumPy:

- Ndarray: Das zentrale Element von NumPy ist das ndarray (N-dimensional Array), das eine effiziente Datenstruktur für das Speichern und Arbeiten mit mehrdimensionalen Arrays darstellt. Diese Arrays können von geringer bis hoher Dimension sein und sind optimiert, um mathematische Operationen auf ganzen Arrays in einem einzigen Schritt auszuführen.

- Universal Functions (ufuncs): NumPy bietet eine breite Palette von mathematischen Funktionen und Operationen, die auf ndarrays angewendet werden können. Diese Funktionen sind vektorisiert, was bedeutet, dass sie auf Elemente in einem Array gleichzeitig angewendet werden, was die Effizienz erheblich steigert.

- Broadcasting: NumPy ermöglicht das Durchführen von Operationen auf Arrays mit unterschiedlichen Formen, indem es die sogenannte "Broadcasting"-Regel verwendet. Dies erleichtert das Arbeiten mit Arrays unterschiedlicher Größe und Form.

- Mathematische Funktionen: Die Bibliothek bietet eine umfangreiche Sammlung von mathematischen Funktionen, statistischen Funktionen und linearen Algebra-Operationen, die für wissenschaftliche und numerische Berechnungen von entscheidender Bedeutung sind.

- Datei-Ein- und Ausgabe: NumPy bietet Funktionen zum Lesen und Schreiben von Daten aus und in verschiedene Formate, einschließlich CSV, Textdateien und binäre Dateien.

- Integration mit anderen Bibliotheken: NumPy wird häufig in Kombination mit anderen wissenschaftlichen Python-Bibliotheken wie SciPy, Matplotlib und Pandas verwendet, um umfangreiche Datenanalysen und wissenschaftliche Simulationen durchzuführen.

Durch seine Fähigkeit, effiziente numerische Berechnungen durchzuführen und umfangreiche Tools zur Verfügung zu stellen, hat NumPy einen wesentlichen Beitrag zur Verbreitung von Python im Bereich des wissenschaftlichen Rechnens geleistet und ist ein unverzichtbares Werkzeug für Datenwissenschaftler, Ingenieure und Forscher.

Dokumentation: [Numpy-Dokumentation](https://numpy.org/doc/stable/)

<a id="Numpy_Allgemeines"><br>

## Allgemeines
</a>

### Das Array

DAS Element in Numpy ist dass Array.  
Ein Array ähnelt auf dem ersten Blick einer Matrix. Wie eine Matrix hat ein Array eine Dimension und genau wie eine Matrix gibt es (fast) keine Begrenzung der Dimensionen. Der große Unterschied eines Numpy-Array ist das nicht alle Rechnungen, welche mit einer Matrix möglich sind auch mit einem Array (einfach) funktionieren. Gleichzeitig sind mit einem Array einige Operationen möglich, welche mit einer Matrix nicht so leicht möglich sein.
<br>

### So sieht ein Array aus

Ein Numpy Array kann zwischen 0-Dimensionen (Eine Zahl) und vielen 100-Dimensionen. Wir betrachten erst mal 1-Dimensionale und 2-Dimensionale Arrays, da 0-Dimensionale langweilig sind und ab 3-Dimensionen bräuchten wir ein Hologramm um das richtig darzustellen. Bei 4-Dimensionalen Arrays = &#x1F92F; 

Ein 1 Dimensionales Array ähnelt einer Liste in Python:
<div style="text-align:center">
arr = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19, ...]
</div>
<br>
Ein 2 Dimensionales Array ist mehr wie eine Tabelle:

| | | | |
|-|-|-|-|
|1|2|3|4|
|2|3|4|5|
|3|4|5|6|
|4|5|6|7|

<br>
Ein 3 Dimensionales Array wären mehrere Tabellen hintereinander. Also jede Tabelle auf einem eigenen Blatt Papier und die Blätte liegen aufeinander.
Ab 5 Dimensionen ist es für uns nicht mehr richtig vorstellbar wie das aussieht. 
<br>

### Begrenzungen des Arrays<br>

- Ein Array muss immer Rechteckig sein. <br> Das bedeutet das ein Array mit zum beispiel 2-Dimensionen und 5 Zeilen und 3 Spalten in jeder Spalte 5 Werte haben muss und in jeder Zeile 3 Werte haben muss.<br> Was nicht gehen würde wäre zum Beispiel ein Array mit 3-Dimensionen (3,3,3), also 3 Zeilen, 3 Spalten und 3 "Schichten" dann darf die 2. Schicht nicht 2 Zeilen und 10 Spalten haben.
- Anders als eine Python Liste sind Numpy-Arrays Homogen das heißt sie können nur eine Art von Daten enthalten. <br> Also zum Beispiel nur Integer oder nur floats oder nur strings ...

<a id="Importieren von Numpy"><br>
    
## Importieren von Numpy
</a> 

Numpy können wir relativ einfach importieren:

```python
import numpy
```

Als alias wird in dieser Dokumentation np gewählt daraus ergibt sich

```python
import numpy as np
```

<a id="Numpy_einfache_Befehle">
    <br><br><br>
    
## Einfache Befehle
</a>

| Befehl                   | Erklärung                                      | Tipp                                        |
|--------------------------|----------------------------------------------|--------------------------------------------|
| `import numpy as np`     | Importiert NumPy und gibt ihm den Alias "np". | Gängige Konvention für NumPy-Import.        |
| `np.array()`             | Erstellt ein NumPy-Array aus einer Sequenz.  | Die Sequenz kann eine Liste oder ein Tupel sein. |
| `np.zeros()`             | Erstellt ein NumPy-Array mit Nullen.         | Legt die Größe und den Datentyp fest.        |
| `np.ones()`              | Erstellt ein NumPy-Array mit Einsen.         | Legt die Größe und den Datentyp fest.        |
| `np.arange()`            | Erstellt ein NumPy-Array mit einer Sequenz von Werten. | Legt den Startwert, das Ende und den Schritt fest. |
| `np.linspace()`          | Erstellt ein NumPy-Array mit einer linearen Sequenz von Werten. | Legt den Start, das Ende und die Anzahl der Werte fest. |
| `np.shape`               | Gibt die Form (Abmessungen) des Arrays zurück. | Nützlich, um die Größe des Arrays zu überprüfen. |
| `np.reshape()`           | Ändert die Form eines Arrays.                 | Passen Sie die neue Form entsprechend an.     |
| `np.sum()`               | Berechnet die Summe der Elemente im Array.    | Nutzen Sie die Achsenparameter für mehr Kontrolle. |
| `np.mean()`              | Berechnet den Durchschnitt der Elemente im Array. | Nutzen Sie die Achsenparameter für mehr Kontrolle. |
| `np.max()`               | Gibt das Maximum im Array zurück.            | Nutzen Sie die Achsenparameter für mehr Kontrolle. |
| `np.min()`               | Gibt das Minimum im Array zurück.            | Nutzen Sie die Achsenparameter für mehr Kontrolle. |
| `np.dot()`               | Führt eine Matrixmultiplikation durch.       | Verwenden Sie dies für Vektor- und Matrixoperationen. |
| `np.concatenate()`        | Verkettet Arrays entlang einer Achse.         | Legen Sie die Achse und die Arrays fest.     |
| `np.random.rand()`       | Erzeugt Zufallszahlen zwischen 0 und 1.      | Passen Sie die Form des Arrays an.            |
| `np.random.randint()`    | Erzeugt Zufallszahlen in einem angegebenen Bereich. | Legen Sie den Bereich und die Form des Arrays fest. |

<a id="Numpy_Beispiele">

## Beispiele:
</a>
<a id="Erstellen eines Arrays"
    
### Arrays erstellen
</a>

Ein Array kann entweder durch umwandeln einer verschachtelteten Python Liste erstellt werden,
oder es wird einfach als ein Array mit den Richtigen Definitionen definiert.

Beispiele:

In [16]:
import numpy as np

PythonListe0 = [1,2,3,4,5,6,7,8,9,10]
PythonListe1 = [[1, 2, 3, 4],[2, 3, 4, 5],[3, 4, 5, 6],[4, 5, 6, 7]]


array0 = np.array(PythonListe0)
array1 = np.array(PythonListe1)

print ('Array0 hat ', array0.ndim, ' Dimensionen')
print (array0)
print ('Array1 hat ', array1.ndim, ' Dimensionen')
print (array1)

Array0 hat  1  Dimensionen
[ 1  2  3  4  5  6  7  8  9 10]
Array1 hat  2  Dimensionen
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


```{admonition} Erklärung:
Zu erst importieren wir Numpy.  
Anschließend definieren wir zwei Listen, eine verschachtelte und eine einfache.  
Diese zwei Listen werden anschließend in 2 arrays umgewandelt.
Beim Überprüfen der Dimensionen der Arrays fällt auf das sich die verschachtelten Listen auf zwei Dimensionen verteilt haben.
```

In [21]:
%reset -f
import numpy as np

array0 = np.zeros((10))
array1 = np.ones((5,5))
array2 = np.empty((3,2,4))

print ('Array0 hat ', array0.ndim, ' Dimensionen')
print (array0, '\n')
print ('Array1 hat ', array1.ndim, ' Dimensionen')
print (array1, '\n')
print ('Array2 hat ', array2.ndim, ' Dimensionen')
print (array2)

Array0 hat  1  Dimensionen
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

Array1 hat  2  Dimensionen
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

Array2 hat  3  Dimensionen
[[[4.95708240e-310 0.00000000e+000 6.82930825e-310 6.82930816e-310]
  [6.82930917e-310 6.82930909e-310 6.82930918e-310 6.82930918e-310]]

 [[6.82930907e-310 6.82930910e-310 6.82930915e-310 6.82930909e-310]
  [6.82930815e-310 6.82930905e-310 6.82930815e-310 6.82930815e-310]]

 [[6.82930918e-310 6.82930905e-310 6.82930905e-310 6.82930910e-310]
  [6.82930909e-310 2.69519842e-115 1.75383197e-109 6.01347002e-154]]]


```{admonition} Erklärung:
Zu erst Importieren wir Numpy.  
Anschließend erstellen wir 3 arrays.  
Eines mit nur Nullen und 1 Dimension, 10 Werte  
Eines nur mit Einsen und 2 Dimensionen, 5 Spalten und 5 Zeilen.  
Als letztes eines mit zufälligen Zahlen und 3 Dimensionen, 4 Spalten, 2 Zeilen und 3 "Schichten".  
(Da es keine "leeren" Arrays geben darf werden die stellen mit Inhalt aus dem Speicher gefüllt)
```
```{admonition} Tipp:
:class: tip
Wenn ihr wissen wollt welche Zahl welche Dimension steuert, merkt man sich am besten:  
"die letzte Ziffer ist für die Spalten, die vorletzte für die Zeilen, und soweiter..."
Das hat den Grund das man auf diese Weise auch mit mehr Dimensionalen Array noch halbwegs klarkommt.
```
<br><a id="Numpy_Daten_erzeugen">

### Daten erzeugen
</a>

Manchmal braucht man Daten mit gewissen Eigenschaften. Um an diese Daten ranzukommen kann man entweder sich sehr viele gedanken Machen und per Hand eine Liste erschaffen welche die geforderten Kriterien erfüllt.
Nach dem das manchmal sehr viel Arbeit sein kann gibt uns Numpy einige Funktionen die Daten erzeugen können.

Linspace generiert Zahlen von einem Startpunkt aus bis zu einem Endpunkt mit einer Bestimmten Anzahl an Zwischenschritten. Die resultierende Liste ist dabei mit gleichmäßig verteilten Zahlen gefüllt. 

In [29]:
%reset -f
import numpy as np

Anfangswert = 0
Endwert = 9
Anzahl0 = 10
Anzahl1 = 24

a = np.linspace(Anfangswert, Endwert, Anzahl0)
b = np.linspace(Anfangswert, Endwert, Anzahl1)

print (a)
print (type(a))
print (b)
print(type(b))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>
[0.         0.39130435 0.7826087  1.17391304 1.56521739 1.95652174
 2.34782609 2.73913043 3.13043478 3.52173913 3.91304348 4.30434783
 4.69565217 5.08695652 5.47826087 5.86956522 6.26086957 6.65217391
 7.04347826 7.43478261 7.82608696 8.2173913  8.60869565 9.        ]
<class 'numpy.ndarray'>


Alternativ zu linspace gibt es auch arange. Anders als bei Linspace gibt man hier nicht die Anzahl der Werte sondern die Schrittweite an. 

```{warning}
Aufgrund von der finiten Genauigkeit von floats, kann es sein das die Ausgabe von arange nicht immer 100% vorhersagbar ist.
```

In [32]:
%reset -f
import numpy as np

Anfangswert = 0
Endwert = 10
Schrittweite0 = 1
Schrittweite1 = 0.3

a = np.arange(Anfangswert, Endwert, Schrittweite0)
b = np.arange(Anfangswert, Endwert, Schrittweite1)

print (a)
print (type(a))
print (b)
print(type(b))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9 4.2 4.5 4.8 5.1
 5.4 5.7 6.  6.3 6.6 6.9 7.2 7.5 7.8 8.1 8.4 8.7 9.  9.3 9.6 9.9]
<class 'numpy.ndarray'>


Ansonsten gibt es noch [logspace](https://numpy.org/doc/stable/reference/generated/numpy.logspace.html#numpy.logspace), [geomspace](https://numpy.org/doc/stable/reference/generated/numpy.geomspace.html#numpy.geomspace) und [mgrid](https://numpy.org/doc/stable/reference/generated/numpy.mgrid.html) um nur ein paar zu nennen. Um mehr zum Thema zu erfahren hat die [Dokumentation extra eine Seite](https://numpy.org/doc/stable/user/how-to-partition.html#how-to-partition) zum erstellen von Werten.

<br><br><a id="Numpy_Daten_aus_Arrays">

### Daten aus Arrays auslesen
</a>

Nachdem wir jetzt ganz viele Daten in unseren Arrays drin haben, möchten wir die auch irgendwie verwenden. Dafür können wir entweder gleich mit den Arrays arbeiten [siehe Array Mathe](#Numpy_Array_Mathe),
oder wir nehmen einzelne Daten (oder teile) aus dem Array raus und rechnen mit denen weiter.

Dafür brauchen wir einige Informationen über unser Array, zum einen wie viele, Dimensionen, "Schichten", Zeilen und Spalten unser Array hat. Zu unserem Glück gibt es eine Funktion die uns genau das sagt: ```np.shape()```
(nur für den Fall das wir es nicht Wissen)

In [118]:
%reset -f
import numpy as np

Array = [[[1, 2],
         [2, 3 ],
         [3, 4 ],
         [4, 5 ]],
        [[11, 12 ],
         [12, 13 ],
         [13, 14 ],
         [14, 15 ]],
        [[21, 22 ],
         [22, 23 ],
         [23, 24 ],
         [24, 25 ]]]

print(np.shape(Array))


(3, 4, 2)


Wenn wir jetzt einen Wert aus aus dem Array haben wollen, müssen wir diesen Wert spezifizieren. Dies machen wir auf die selbe weise wie wir sie generiert haben.  
Also "die letzte Ziffer ist für die Spalten, die vorletzte für die Zeilen, und soweiter..."

Solange wir das im kopf behalten ist alles gut.

In [128]:
print('Das gesamte Array lautet:')
print(Array)
print('Die erste "Schicht" des Arrays lautet:')
print(Array[0])
print('Die erste Spalte in der ersten Schicht des Arrays lautet:')
print(Array[0][0])
print('Die erste Stelle in der ersten Spalte in der ersten Schicht des Arrays lautet:')
print(Array[0][0][0])

Das gesamte Array lautet:
[[[1, 2], [2, 3], [3, 4], [4, 5]], [[11, 12], [12, 13], [13, 14], [14, 15]], [[21, 22], [22, 23], [23, 24], [24, 25]]]
Die erste "Schicht" des Arrays lautet:
[[1, 2], [2, 3], [3, 4], [4, 5]]
Die erste Spalte in der ersten Schicht des Arrays lautet:
[1, 2]
Die erste Stelle in der ersten Spalte in der ersten Schicht des Arrays lautet:
1



<br>
<br><a id="Numpy_Lesen_und_Schreiben">

### Lesen und Schreiben von Dateien
</a>
Numpy kann Dateien lesen und schreiben. Numpy hat sogar ein eigenes Dateiformat um Arrays für spätere Nutzung zu speichern. Diese Dateien können allerdings nur von Numpy gelesen werden, deswegen kommen diese auch nur überausselten in diesem Format aus einem Messgerät raus. Der CSV-Datei dagegen kommt man deutlich häufiger über den Weg. Aus diesem Grund beschäftigen wir hier uns erst mal nur mit der CSV Datei (und ihren Unterarten).   
CSV steht für Comma Seperated Values, also mit Komma getrennte Werte. Wenn wir uns so eine CSV Datei anschauen stellen wir tatsächlich fest es sich tatsächlich einfach um werte handelt welche mit einem Komma separiert wurden:

```CSV
hero,description
batman,uses technology
superman,flies through the air
spiderman,uses a web
ghostrider, rides a motorcycle
```

Ganz oben ist oft ein Head, also eine Zeile, welche den Inhalt der Spalten erklärt.
Darunter befinden sich dann unsere Daten. Hin und wieder gibt es Files bei denen nicht das Komma das Trennzeichen zwischen den Daten ist, zum Beispiel ein Tab, dann handelt es sich zwar *eigentlich* nicht mehr um eine CSV. Dennoch ändert sich die Syntax nur minimal, dann müssen wir halt Numpy nur den Denominator, also das Trennzeichen, noch angeben.

Es gibt noch viel mehr zu CSV Dateien zu erklären, wen das Interressiert kann einfach mal [hier schauen](https://de.wikipedia.org/wiki/CSV_(Dateiformat))
<br><br>

Nachdem wir ja schon wissen das Numpy-Arrays immer die gleiche form haben müssen und keine Leerstellen vertragen müssen wir uns entscheiden wie wir mit Fehlstellen in unserer Datei umgehen. Dazu haben wir zwei Möglichkeiten:

1. Wir sind uns sicher das es keine Fehlstellen gibt: wir benutzen [```np.loadtext```](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy.loadtxt)
2. Wir sind uns nicht sicher das es keine Fehlstellen gibt: wir benutzen [```np.genfromtext```](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html#numpy.genfromtxt)

Das problem bei ```np.genfromtext``` ist, dass es deutlich Arbeitsintensiver für den Computer ist als ```np.loadtext``` und damit auch deutlich langsamer.
Im folgenden werden wir aber beide mit einem Beispiel bearbeiten.

<a id="Numpy_loadtext">

#### loadtext
</a>

Um die obersten Zeilen zu überspringen geben wir den Parameter ```skiprows=``` an dieser ist nicht zwingend erforderlich, damit überspringen wir aber den Header also alle Zeilen die nicht unsere Daten sind.

Um das Trennzeichen anzugeben benutzen wir ```delimiter=""``` da der Standart delimiter Leerzeichen sind müssen wir hier ein Komma angeben

enn wir nicht alle Spalten haben wollen können wir mit ```usecols=``` entweder eine bestimmte (ein int.) oder mehrere Spalten auslesen (da brauchen wir ein tupel mit allen gewollten Spalten). Die Zählung beginnt bei 0. Für die 1. Spalte müssten wir also ```usecols=0``` verwenden und für die Spalten 3-7: ```usecols=(4,5,6,7,8)```

In dem unteren Beispiel geht es nur um die simple Syntax, für mehr Information schaut in die [Dokumentation zu loadtext](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy.loadtxt)

In [50]:
%reset -f
import numpy as np
from io import StringIO   # StringIO verhält sich wie File und dient hier nur als Platzhalter 

c = StringIO("Zahl1,Zahl2 \n 0, 1\n 2, 3")

# das hier würde einen Fehler Produzieren da in der ersten Zeile stings sind und in den anderen int.
#Array = np.loadtxt(c) 

Array = np.loadtxt(c, skiprows=1, delimiter=",")

print(Array)
print('Dass Array hat ',Array.ndim, ' Dimensionen')

[[0. 1.]
 [2. 3.]]
Dass Array hat  2  Dimensionen


<a id="Numpy_genfromtext">

#### genfromtxt
</a>

Um die obersten Zeilen zu überspringen geben wir den Parameter ```skip_header=``` an dieser ist nicht zwingend erforderlich, damit überspringen wir aber den Header also alle Zeilen die nicht unsere Daten sind.

Um das Trennzeichen anzugeben benutzen wir ```delimiter=""``` da der Standart delimiter Leerzeichen sind müssen wir hier ein Komma angeben ``` delimiter=","```

Wenn wir nicht alle Spalten haben wollen können wir mit ```usecols=``` entweder eine bestimmte (ein int.) oder mehrere Spalten auslesen (da brauchen wir ein tupel mit allen gewollten Spalten). Die Zählung beginnt bei 0. Für die 1. Spalte müssten wir also ```usecols=0``` verwenden und für die Spalten 3-7: ```usecols=(4,5,6,7,8)```

Wenn ```genfromtxt``` auf eine Fehlende Stelle trifft dann ersetzt es die Fehlstelle durch ein nan string ersetzt. Dieses verhalten lässt sich mit ```missing_values``` und ```filling_values``` verändern.

```missing_values=""``` ersetzt Fehlstellen durch einen von euch definierten String.  
```filling_values=``` ersetzt Fehlstellen mit einem von euch definierten Wert.

In dem unteren Beispiel geht es nur um die simple Syntax, für mehr Information schaut in die [Dokumentation zu genfromtext](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html#numpy.genfromtxt)

In [69]:
%reset -f
import numpy as np
from io import StringIO   # StringIO verhält sich wie File und dient hier nur als Platzhalter 

a = StringIO("Zahl1,Zahl2 \n 0, 1\n 2, 3 \n ,5")
b = StringIO("Zahl1,Zahl2 \n 6, 7\n 8, 9 \n ,11")

Fehlstellen = 'Q'

Array0 = np.genfromtxt(a, skip_header=1, delimiter=",")
Array1 = np.genfromtxt(b, skip_header=1, delimiter=",", filling_values= 0)

print(Array0)
print('Dass Array hat ',Array0.ndim, ' Dimensionen \n')
print(Array1)
print('Dass Array hat ',Array1.ndim, ' Dimensionen')


[[ 0.  1.]
 [ 2.  3.]
 [nan  5.]]
Dass Array hat  2  Dimensionen 

[[ 6.  7.]
 [ 8.  9.]
 [ 0. 11.]]
Dass Array hat  2  Dimensionen


<a id="Numpy_Array_Mathe"><br><br>

### Array Mathe
</a>
<a id="Numpy_Klassische_Algebra"

#### "Klassische" Algebra
</a>

Mit numpy kommen jede menge Funktionen die wir alle kennen wie zum Beispiel $cos$ oder $\sqrt{}$
für eine Vollständige liste einfach in die [Dokumentation](https://numpy.org/doc/stable/reference/routines.math.html) schauen. 

|Funktion|numpy equivalent|
|:------:|:--------------:|
|$cos(x)$|np.cos(x)|
|$sin(x)$|np.sin(x)|
|$\sqrt{x}$|np.sqrt(x)|
|$\vdots$|$\vdots$|
|<hr>|<hr>|
|Umwandlung Rad in Grad|np.degrees()|
|Umwandlung Grad in Rad|np.rad()|
|$\vdots$|$\vdots$|
|<hr>|<hr>|
|$e^x$|np.exp(x)|
|$log_{10}(x)$|np.log10()|
|$ln()$|np.log()|
|$\vdots$|$\vdots$|
|<hr>|<hr>|
|$x^{-1}$|np.reciprocal()|
|$\vdots$|$\vdots$|


Das wichtige für uns ist das alle diese Funktion nicht nur mit einzelnen werten funktionieren sondern auch mit Arrays dabei werden die Werte einzeiln aus dem array rausgenommen mit der funktion neu bestimmt und wieder eingefügt. 

Auch lassen sich Arrays direkt miteinander verrechnen zum Beispiel kann man Array1 und Array2 Addieren und bekommt Array3, bei dem sämtliche Elemente aus der Addition der entsprechenden elemente in den anderen beiden Arrays bestehen.

In [98]:
import numpy as np

Array1 = np.ones((5,5))
Array2 = np.zeros((5,5))

Array3 = np.ones((1,5))
Array4 = np.zeros((1,5))

Array5 = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])

Array6 = Array1 + Array1

Array7 = np.sin(Array5)

Array8 = Array6 - Array7

Array9 = Array1 * Array3 

Array10 = Array6 * Array5

Array11 = Array5 * Array2 

Array12 =Array1 * 8 


print('Array1 =', '\n',Array1, '\n')
print('Array2 =', '\n',Array2, '\n')
print('Array3 =', '\n',Array3, '\n')
print('Array4 =', '\n',Array4, '\n')
print('Array5 =', '\n',Array5, '\n')
print('Array6 =Array1 + Array1', '\n',Array6, '\n')
print('Array7 =np.sin(Array5)', '\n',Array7, '\n')
print('Array8 =Array6 - Array7', '\n',Array8, '\n')
print('Array9 =Array1 * Array3 ', '\n',Array9, '\n')
print('Array10 =Array6 * Array5', '\n',Array10, '\n')
print('Array11=Array5 * Array2 ', '\n',Array11, '\n')
print('Array12=Array1 * 8 ', '\n',Array12, '\n')


Array1 = 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

Array2 = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

Array3 = 
 [[1. 1. 1. 1. 1.]] 

Array4 = 
 [[0. 0. 0. 0. 0.]] 

Array5 = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Array6 =Array1 + Array1 
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]] 

Array7 =np.sin(Array5) 
 [[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]
 [ 0.91294525  0.83665564 -0.00885131 -0.8462204  -0.90557836]] 

Array8 =Array6 - Array7 
 [[2.         1.15852902 1.09070257 1.85887999 2.7568025 ]
 [2.95892427 2.2794155  1.3430134  1.01064175 1.58788151]
 [2.54402111 2.99999

 Natürlich gibt es auch extra Befehle welche sich auf Matrizen beziehen wie etwa Transponieren oder die Form verändern. Für eine Übersicht über alle Befehle ein Blick in [die entsprechende Dokumentation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

In [113]:
import numpy as np

Matrix = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])

MatrixTransponiert = Matrix.T

Matrix2 = np.reshape(Matrix, (2,10))

Matrix3 = np.transpose(Matrix2)

print('Matrix = \n', Matrix, '\n')
print('Matrix Transponiert = \n', MatrixTransponiert, '\n')
print('Matrix 2 = \n', Matrix2, '\n')
print('Matrix 2 Transponiert = \n', Matrix3)

Matrix = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Matrix Transponiert = 
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] 

Matrix 2 = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

Matrix 2 Transponiert = 
 [[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]
